import { Controller, Post, Body, Res, BadRequestException } from '@nestjs/common';
import { Response } from 'express';
import { DiagramEngine } from './diagram.engine';
import archiver from 'archiver';

@Controller('api/generate')
export class GenerateController {
  constructor(private readonly engine: DiagramEngine) {}

  @Post()
  generate(@Body() body: { diagramId?: string; graph?: { nodes: any[]; edges: any[] } }) {
    return this.engine.generate(body);
  }

  @Post('download')
  async download(
    @Body() body: { diagramId?: string; graph?: { nodes: any[]; edges: any[] } },
    @Res() res: Response,
  ) {
    const { validation, result } = await this.engine.generate(body);

    if (!validation.valid || !result) {
      throw new BadRequestException({
        message: 'Diagram has validation errors',
        errors: validation.errors,
      });
    }

    res.set({
      'Content-Type': 'application/zip',
      'Content-Disposition': 'attachment; filename="generated-code.zip"',
    });

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.pipe(res);

    for (const file of result.files) {
      archive.append(file.content, { name: file.path });
    }

    archive.append(this.buildReadme(result), { name: 'README.md' });
    await archive.finalize();
  }

  private buildReadme(result: { summary: any; tree: string }): string {
    const s = result.summary;
    return `# Generated CQRS Code

Generated by MediatorFlow Visual Architecture Designer.

## Summary
- Commands: ${s.commands}
- Queries: ${s.queries}
- Events: ${s.events}
- Consumers: ${s.consumers}
- Behaviors: ${s.behaviors}
- Aggregates: ${s.aggregates}
- Total files: ${s.totalFiles}

## File Tree
\`\`\`
${result.tree}
\`\`\`

## Next Steps
1. Copy the generated \`src/\` files into your NestJS project
2. Register the handlers, consumers, and behaviors in your module's \`providers\` array
3. Search for \`// TODO:\` comments and implement your business logic
4. Run \`tsc --noEmit\` to verify there are no compilation errors
`;
  }
}
